version: "3"

services:
  app:
    container_name: portfolio-app
    image: portfolio-app
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - portfolio_network
    restart: always

networks:
  portfolio_network:
    name: portfolio_network
